version: '3.9'
services:
    mysql:
        container_name: mysql-DB
        volumes:
            - './data/prestashop_DB:/var/lib/mysql'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - '3307:3306'
        image: mysql:5.7
    prestashop:
        container_name: prestashop-web
        volumes:
            - './data/prestashop:/var/www/html'
        restart: always
        environment:
            - DB_SERVER=mysql
        ports:
            - '8080:80'
        image: prestashop/prestashop
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        command: --schedule "0 5 * * 1" --cleanup --debug
    dbBackup:
        image: fradelg/mysql-cron-backup
        depends_on:
            - mysql
        restart: always
        volumes:
            - ./data/database_backup:/backup
        environment:
            - MYSQL_USER=root
            - MYSQL_PASS=admin
            - MYSQL_DB=prestashop
            - CRON_TIME=55 23 * * *
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - TIMEOUT=10s
            - INIT_BACKUP=1

volumes:
  mysql: 
  prestashop: 
  watchtower:
  bdBackup:
  