<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyhp8kg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyhp8kg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTyhp8kg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTyhp8kg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTyhp8kg\appProdProjectContainer([
    'container.build_hash' => 'Tyhp8kg',
    'container.build_id' => '73693497',
    'container.build_time' => 1620879045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyhp8kg');
